apiVersion: api.tsb.tetrate.io/v2
kind: Organization
metadata:
  name: coreos-0-org
---
apiversion: api.tsb.tetrate.io/v2
kind: Tenant
metadata:
  organization: coreos-0-org
  name: coreos-0-tenant
---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  organization: coreos-0-org
  tenant: coreos-0-tenant
  name: coreos-0-ws
spec:
  namespaceSelector:
    names:
      - "*/bookinfo"
      - "*/bookinfo-tier1"
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  name: coreos-0-gg
  organization: coreos-0-org
  tenant: coreos-0-tenant
  workspace: coreos-0-ws
spec:
  configMode: BRIDGED
  namespaceSelector:
    names:
      - "*/*"
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: ingress-bookinfo
  workspace: coreos-0-ws
  tenant: coreos-0-tenant
  group: coreos-0-gg 
  organization: coreos-0-org
spec:
  workloadSelector:
    namespace: bookinfo
    labels:
      app: tsb-gateway-bookinfo
      istio: ingressgateway
  http:
  - name: bookinfo
    port: 80
    hostname:  coreos-01-bookinfo.cx.tetrate.info
    routing:
      rules:
      - route:
          host: bookinfo/productpage.bookinfo.svc.cluster.local
          port: 9080
  - name: details
    port: 9080
    hostname: details.cx.tetrate.info
    routing:
      rules:
      - route:
          host: bookinfo/details.bookinfo.svc.cluster.local
          port: 9080          
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Tier1Gateway
metadata:
  name: bookinfo-tier1
  workspace: coreos-0-ws
  tenant: coreos-0-tenant
  group: coreos-0-gg 
  organization: coreos-0-org
spec:
  workloadSelector:
    namespace: bookinfo-tier1
    labels:
      app: tsb-gateway-bookinfo-tier1
  externalServers:
  - name: bookinfo
    hostname: coreos-01-bookinfo.cx.tetrate.info
    port: 80
    tls: {}
    