---
apiVersion: v1
kind: Namespace
metadata:
  name: es
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
 name: tsb 
 namespace: es 
spec:
 version: 7.13.2
 http:
   service:
     spec:
       type: LoadBalancer
 nodeSets:
   - name: master
     count: 1
     config:
       node.master: true
       node.data: false
       node.ingest: false
     podTemplate:
       spec:
         containers:
           - env:
               - name: ES_JAVA_OPTS
                 value: -Xmx4g -Xms4g
             name: elasticsearch
             resources:
               limits:
                 memory: 6Gi
         initContainers:
           - command:
               - sh
               - -c
               - sysctl -w vm.max_map_count=262144
             name: set-max-map-count
             resources: {}
             securityContext:
               privileged: true
   - name: data
     count: 3
     config:
       node.master: false
       node.data: true
       node.ingest: true
     podTemplate:
       spec:
         containers:
           - env:
               - name: ES_JAVA_OPTS
                 value: -Xmx4g -Xms4g
             name: elasticsearch
             resources:
               limits:
                 memory: 6Gi
         initContainers:
           - command:
               - sh
               - -c
               - sysctl -w vm.max_map_count=262144
             name: set-max-map-count
             resources: {}
             securityContext:
               privileged: true
     volumeClaimTemplates:
       - metadata:
           name: elasticsearch-data
         spec:
           accessModes:
             - ReadWriteOnce
           resources:
             requests:
               storage: 100Gi
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
 name: tsb
 namespace: es
spec:
 version: 7.9.0
 count: 1
 elasticsearchRef:
   name: tsb
 http:
   service:
     spec:
       type: LoadBalancer

