apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-gke-tsb
  namespace: tsb
spec:
  acme:
    email: petr@tetrate.io
    preferredChain: "ISRG Root X1"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-issuer-gke-tsb-account-key
    solvers:
    - selector:
        dnsZones:
          - cx.tetrate.info
      dns01:
        route53:
          region: us-east-1
          accessKeyID: AKIASZYLIE45QPKJR6AT
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: secret-access-key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tsb-certs
  namespace: tsb
spec:
  secretName: tsb-certs
  issuerRef:
    name: letsencrypt-gke-tsb
    kind: ClusterIssuer
  dnsNames:
  - coreos-01.cx.tetrate.info
