---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: xcp-trust-anchor
  namespace: tsb
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJRENDQWdpZ0F3SUJBZ0lSQVBaUEJKVlRpWG9xOG9HVmN1c2dLa2t3RFFZSktvWklodmNOQVFFTEJRQXcKR1RFWE1CVUdBMVVFQXhNT2VHTndMblJsZEhKaGRHVXVhVzh3SUJjTk1qSXdOREU1TVRreE5qRTFXaGdQTWpFeQpNakF6TWpZeE9URTJNVFZhTUJreEZ6QVZCZ05WQkFNVERuaGpjQzUwWlhSeVlYUmxMbWx2TUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdFgyNXUxRHFlNFZGV1hsc0lwWEdsUWcyRXI4UTZkekoKQTFTb21yYmJOQ0oyQ2JsTEw5Um1HVk5RN2M5YjRUcmxMY2VaWXhob1REZlJPTC9BbDMxWjBXNVkvYUNBZW9MbgpmaWMrK3JCeStpc082WW1CUlltWWJQandBdHRXenoxeDlBRUt0c2U4bzkraUhhVXZtS0lKNU84M2syRXViMDkwClhvTmEvUWcyQ1k3OWpjUWowQU5QZkxWSlpWVGJ1MDF4emtzdTZNMGtSSDB5S2FmRm1vWi9hbllwRzQyWnFvRVgKbnVpb2p3dzhPVmg0SzE0STRKbWlBMFVibGxybGg5dkdVR2x5Y1ZuWjJEK3VTVWdLcitOaFo5TWxlYVkwRHJzTwp2cDNodU56SXFEU0ludSt5bTJIamJ1d1o2UkZEZldBN2NSem41OVJYUGpmMWpMUGJVcmNVaXdJREFRQUJvMkV3Clh6QU9CZ05WSFE4QkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUMKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkJZOXpNbkpXbUs3Ui9nVEZZUTlJY0JKeHc1bQpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUN4TFFKcE83NzZhbGxPcXRFTFJuYzY0dUFGbndYZmEvSFBkdFA3ClZkaUtzWmxGdjAwbUxkVS9LcnVyeHVTZEplSy82bk43VGhuZHowdE1TTThPb3UvcDZ5RnFOREQ1dytDWUNUNUMKczRIeEViWHZXRitWMlpzTnpJRm1RWUNSUXo3NjZlelZERUx1T2tkTTBrYmtWSE94cE9ORDNiS2cyWnNXVGsxVQo3UVdMK0tPcFlTZWI4OXRua2ErOGV1czlyM3VQZ1plR1o5NnM1TGxHSzF5dHNnNkNCbjFKdmtHMzZXYktKMGxTCjNCanNrbFdlTUVjaWZDakFqMmRBeGNiVUtIYW4yTy9ZUzR0Szl3Wmp2RTZhbWpWK2UraXRQZy8rVlIwSWNTRzAKaEdWWFpma1FUWFY4a1liTDhTVWJ3Vktkcm45dlFIT01sUjNSU1FqbDgvQmhxRTNmCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdFgyNXUxRHFlNFZGV1hsc0lwWEdsUWcyRXI4UTZkekpBMVNvbXJiYk5DSjJDYmxMCkw5Um1HVk5RN2M5YjRUcmxMY2VaWXhob1REZlJPTC9BbDMxWjBXNVkvYUNBZW9MbmZpYysrckJ5K2lzTzZZbUIKUlltWWJQandBdHRXenoxeDlBRUt0c2U4bzkraUhhVXZtS0lKNU84M2syRXViMDkwWG9OYS9RZzJDWTc5amNRagowQU5QZkxWSlpWVGJ1MDF4emtzdTZNMGtSSDB5S2FmRm1vWi9hbllwRzQyWnFvRVhudWlvand3OE9WaDRLMTRJCjRKbWlBMFVibGxybGg5dkdVR2x5Y1ZuWjJEK3VTVWdLcitOaFo5TWxlYVkwRHJzT3ZwM2h1TnpJcURTSW51K3kKbTJIamJ1d1o2UkZEZldBN2NSem41OVJYUGpmMWpMUGJVcmNVaXdJREFRQUJBb0lCQUhGazYwMjR3YmlKVFFvWgpUbEhSaUxDRzM5b1luTVd4VjdxSUE0d2U0WmlTUzNQSjNNczJodEFkK1R1TVNsalFCbTd5L2NnbmNNcm1PUWVlCjd3TDNvODJ4aDFKNEhLM3U2aG90QlRGMlczQW94UGx2RzJES0ZuMUhrQllJMnhWQ3k5YnJhN2xGMUh3Qzl2UlUKeUFjeWZzSVdJSUFwd094MUZUMFVEeDUzS2VRUDhKYmxEc3A3T0hzdUY3azQvUG5NU0FpVmt6bExKdE5XNWlsWQpJWlIrbThqZUhldFBQRW1hcUxndmxEZGtNenpMNDlXL3h5dTJWNDErRFVCOW5TWk9ZVHlpU1p0YkZERDBlZU1UCmd1WFU1N3BHOEJwNVhPbjB5WDNSdGF3NVNMMUdPeHg2UEprTXZhcjQyNjhvd2ZKN0RWekdSYVJpYW9weDNsS28KRk9HTUlhRUNnWUVBejBaVHhHMFZXSjRIM0NxMzN3cXZvckcrUzhVUUpPMHZaR3hUd1M1QnNRTEhabnFJejVpeQprVTFqT2pLWkg1U29sM1VCYjhsdU1ib0hraitXam1OelhqbmQ1ZnJGdm5VeWIxZTlpMTR4N3VyR0tBMmFKbVdaCjNHTDZwSktYSFV1N2JYQUFQQzFxbU9aeTd0L1Z5MHA0VFhVVzJmc3JwUUo2bGZ0U1lZdDdhckVDZ1lFQTRDZkIKa0JZR0dPUUFKQnFSUHA1UXRlcTMzVmF0VmVDL3o4MGJPeUZRQTZzL200bjEzazFPcFFLcHZ4RjBXaU5KOWRKQgpGV0lWZ1VldnBKNkQvQmE4MlVlNFRoMUlqZmtia2ZYTlovOC8zU281L3Q2MG40bEZmSmNaV1NpbmlDdnJtOTZvCllpSkNNcXZMTWtBdzAvYkgyRzIvNFNmNG56ODRNNFQyT0RRWlNmc0NnWUVBdFRVbm9LODVIVHN6WmZEV3hTRGoKZ2RuZ292OUthTzRQSTcxc3o1T3dESitBVWdCSVFTMmUxMWNQcTk1MmJkeWFNNmN3TlZtbGc4VytQc1pteWw3NQppbVFPc2JPMlV4YkVuQURhRGRDdzJNM1pwVVNYQW9DS3JkaStoVWcrNG5iR0Nod0RxSmlQKzlKa29wOS9tbldsCmpSb1RlMGlSMUhYQlZBUGU5clpwbEZFQ2dZQmQwWVg4YnB0aXM1c3pnVU1sZUZIRHNsZitkaGJhaU5UL2ZwTlYKTGw0MUN1bjJpY20wbjVxNUNlSk9MRm9NbUJTT3BNL0V5V2JDMDJRNmZIWTFmcmJRSW1xTGwwb1UwaHl0L0xsYQpPOFZaSmlGY0FZNkw3NEo3NFNvazNSVXhzMkJMdnVldkd6T2x6YTJnZktsekxpajY5d1NHa3BwRzNNa0RGeldPCjFJOTVIUUtCZ0hlMHh0SFZxdnd5N1lyTkNaVHlROW11V1B1akVBakRRVlJ1emoyTm5lSGRvOEtNK3NmYjEreTIKVFI0V2dkaXRxaXl1a01OK1hsRmt3M0ZzeDlSN3pUeTlkQWhEUUR0dWVLMXY3VmhzUVBBMTFhUnFjYnNZa2diVAp4RitDd1lYdVZ4QktWTVVIaUlPNXUrVGx4MG5idGJXUlNQSWY1WWhtK0V0RW1XOHVXcmw4Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: xcp-trust-anchor
  namespace: tsb
spec:
  ca:
    secretName: xcp-trust-anchor
---
# to create root CA
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xcp-identity-issuer
  namespace: tsb
spec:
  secretName: xcp-identity-issuer
  issuerRef:
    name: xcp-trust-anchor
    kind: Issuer
  duration: 30000h
  isCA: true
  commonName: ca.xcp.tetrate.io
  uris:
    - spiffe://xcp.tetrate.io/ca
  usages:
    - cert sign
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: xcp-identity-issuer
  namespace: tsb
spec:
  ca:
    secretName: xcp-identity-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xcp-central-cert
  namespace: tsb
spec:
  secretName: xcp-central-cert
  issuerRef:
    name: xcp-identity-issuer
    kind: Issuer
  duration: 30000h
  isCA: false
  dnsNames:
    - "${DEPLOYMENT_NAME}"-tsb."${DNS_DOMAIN}"          
    - tsb."$OCP_DOMAIN"
    - "central.xcp.tetrate.io"
  uris:
    - spiffe://xcp.tetrate.io/central
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mpc-certs
  namespace: tsb
spec:
  secretName: mpc-certs
  issuerRef:
    name: xcp-identity-issuer
    kind: Issuer
  duration: 30000h
  isCA: false
  dnsNames:
    - "mpc.tsb.svc.cluster.local"
  uris:
    - spiffe://xcp.tetrate.io/mpc
---
