apiVersion: install.tetrate.io/v1alpha1
kind: ControlPlane
metadata:
  name: controlplane
  namespace: istio-system
spec:
  hub: $REPO
  telemetryStore:
    elastic:
      host: $DEPLOYMENT_NAME-tsb.$DNS_DOMAIN
      port: 8443
  managementPlane:
    host: $DEPLOYMENT_NAME-tsb.$DNS_DOMAIN
    port: 8443
    clusterName: $CLUSTER
    organization: $ORG
