apiVersion: install.tetrate.io/v1alpha1
kind: ControlPlane
metadata:
  name: controlplane
  namespace: istio-system
spec:
  hub: $REPO
  telemetryStore:
    elastic:
      host: $BRIDGE_ADDRESS_TSB
      port: $PORT_TSB
      selfSigned: true
  managementPlane:
    host: $BRIDGE_ADDRESS_LB
    port: $PORT_LB
    clusterName: $CLUSTER
    organization: $ORG
    selfSigned: true
