apiVersion: install.tetrate.io/v1alpha1
kind: ControlPlane
metadata:
  name: controlplane
  namespace: istio-system
spec:
  hub: $REPO
  telemetryStore:
    elastic:
      host: ${ES_FQDN}
      port: 9200
      selfSigned: true
      version: 7
  managementPlane:
    host: $DEPLOYMENT_NAME-tsb.$DNS_DOMAIN
    port: 8443
    clusterName: $CLUSTER
    organization: $DEPLOYMENT_TYPE-$DEPLOYMENT_NAME-org
